[env:megaatmega2560-configurable]
build_flags =
    ${env:megaatmega2560.build_flags}
    -DFEATURE_MODULE_LOGGING=1
    -DFEATURE_MODULE_SECONDARY_SERIAL=0
    -DFEATURE_MODULE_COMMS_EXTENDED=1
    -DFEATURE_MODULE_TABLE_SWITCHING=0
    -DFEATURE_MODULE_ENGINE_PROTECTION=1
    -DFEATURE_MODULE_LAUNCH_FLATSHIFT=0
    -DFEATURE_MODULE_FAN_AIRCON=1
    -DFEATURE_MODULE_NITROUS=0
    -DFEATURE_MODULE_ADVANCED_ENGINE=1
    -DFEATURE_ADVANCED_BOOST=1
    -DFEATURE_ADVANCED_VVT=1
    -DFEATURE_ADVANCED_WMI=0
    -DFEATURE_ADVANCED_LAUNCH_FLATSHIFT=0
    -DSPEEDUINO_FEATURE_CONFIGURED=1
build_src_filter =
    +<*>
    -<modules/secondary_serial/module_secondary_serial.cpp>
    -<modules/secondary_serial/secondary_serial.cpp>
    -<modules/table_switching/module_table_switching.cpp>
    -<modules/table_switching/page_registry_tables.cpp>
    -<modules/table_switching/secondaryTables.cpp>
    -<modules/launch_flatshift/module_launch_flatshift.cpp>
    -<modules/launch_flatshift/launch_flatshift.cpp>
    -<modules/nitrous/module_nitrous.cpp>
    -<modules/nitrous/nitrous.cpp>

; generated profile: street
